# Site settings
title: asra.dev
author: "RoseAppleTree"
author_avatar: /images/header.jpg
email: alias@domain.tld
description: some desc here
url: "https://dongyadoit.com"
domain: "http://dongyadoit.com"
github_username: rozeappletree
github_site_repo: rozeappletree/blog-template
disqus: blog-template-3


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


gems:
  - jekyll-sitemap
